### ISSUE TITLE
Add homebrew formula

### ISSUE THREAD

**Issue by halffullheart** [halffullheart/mdr#17]
Add a homebrew formula. Info here: https://github.com/mxcl/homebrew/wiki/Formula-Cookbook

**Comment by kud** [comment]
Wow, wow wow. Thanks @halffullheart but I'm already on it if you don't mind ;) I just need to be sure that rake release on macosx works well and I'm ok with the formula :p

**Comment by halffullheart** [comment]
Go for it. I just wanted to track that we plan to do this.

**Comment by kud** [comment]
Perfect! ;)

**Comment by kud** [comment]
Do you confirm that I need to `rake` first to compile and `rake release` to create the binary? Coz release directly doesn't work, still need appIcon.png.

**Comment by kud** [comment]
https://github.com/mxcl/homebrew/pull/24050

You certainly should tag your versions, @halffullheart :)

I'm not sure that "latest" version will be accepted by homebrew community.

**Comment by kud** [comment]
Please, please, @halffullheart, tag your commits! I can't publish my homebrew task without it! https://github.com/mxcl/homebrew/pull/24050#discussion_r7510178 poke @madx

**Comment by madx** [comment]
@kud, @halffullheart is in the PST time zone, so there's no need to poke him twice while he sleeps ;-)

There already was a 1.0 version, maybe we could tagbit back. Also, semver should be used!

**Comment by kud** [comment]
Yep but cant wway

**Comment by kud** [comment]
Cant wait*

**Comment by halffullheart** [comment]
@kud I have fixed the problem with rake release. That should be all that is needed to compile now for the homebrew formula.

I also tagged the latest commit with v1.0.0-beta.2. This should be sufficient for the homebrew formula and then we can figure out what will be needed to make this a 1.0.0!

I would also like to come up with a better way to manage bumping versions, and I have opened #22 to that effect.

**Comment by kud** [comment]
Lovely! Thanks a lot!

On 8 November 2013 08:07, Daniel Worthington notifications@github.comwrote:

> Closed #17 https://github.com/halffullheart/mdr/issues/17.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/halffullheart/mdr/issues/17
> .

## 

_Erwann Mest_

kud.io
