### ISSUE TITLE
Improve the mac version look-and-feel

### ISSUE THREAD

**Issue by jlecour** [halffullheart/mdr#2]
Hi,

Like I've said earlier, I've been using `mdr` for years on my Mac and I'm so glad it exists, even with its imperfections.

Since it's reviving from its ashes, are some "wishes" : 
1. Improve copy/paste : 
   - Cmd-C doesnt copy the selected text
   - spaces are in fact [em space](http://www.fileformat.info/info/unicode/char/2003/index.htm)
   - text selection takes both columns and line numbers instead of just the code in the current column
2. add a link/button to fold a file in a multi-file diff, which would be very useful for code reviews
3. add a link/button to open the current file in the text editor, at the corresponding line.
4. until the window is clicked, Page-up/down keys are inactive (I get an error sound), even if `mdr` is the frontmost/active application.

Sadly, I have absolutely no skills in Mac development (only Ruby) so I'm unable to help with the code. However, I'm an intensive user of `mdr` so I can help test/debug as much as possible.

Thank you so much for releasing the code and taking care of it a little more.

**Comment by jlecour** [comment]
Since `mdr` is a web view, maybe there would be something to do with [codemirror](http://codemirror.net/).

It's been used in the Safari [web inspector](https://www.webkit.org/blog/2518/state-of-web-inspector/#source-code) for a few months.

I don't know, maybe it's too much work, or tot much overkill for what we need in `mdr`, but I've just thought about it.

**Comment by madx** [comment]
Hi Jérémy,

Just a note to say that most of what you propose could be available on other platforms as well (except your Cmd-C and Page up/down problem)

You may not have skills with Cocoa dev, but since it's only a WebView, I'm sure you could add some tweaks here and there in the HTML generation process (in Reader.c)

I might take a look at this once I'm done with the GTK/WebKit port

Cheers

**Comment by kud** [comment]
:heart:  :shipit: !!!!

**Comment by madx** [comment]
In fact, I'm creating dedicated issues for points 1.3, 2 and 3 so we can work on them as smaller chunks and since they would be useful for everyone.

**Comment by halffullheart** [comment]
I’m closing this since there are now smaller issues addressing all these points.

Cmd-C doesn’t copy: #10
Em-spaces: #11
Folding: #9
Linking to file in text editor: #8
Page-up/down keys: #12

**Comment by kud** [comment]
![dance-jcvd](https://f.cloud.github.com/assets/655838/1471812/dc8bee8c-45f1-11e3-9bbc-296c18187aa8.gif)
