### ISSUE TITLE
Compile against WebKit on Ubuntu

### ISSUE THREAD

**Issue by madx** [halffullheart/mdr#21]
On my Arch I can compile the Linux frontend which uses `webkit2.h` but the seems to be impossible on Ubuntu.

Basically there are two choices:
- See if WebKit2 is available on Ubuntu and go on with this change
- Revert to WebKit1 for all Linux flavors since this is most common

**Comment by halffullheart** [comment]
Is there a significant benefit to using WebKit 2? It sounds like WebKit 1 is more compatible. I’m not super familiar with Linux but I wasn’t able to find a package for Ubuntu after a fair bit of searching. Maybe I just don’t know where to look.

I’m leaning towards switching to WebKit 1. I will check in my Vagrant file which will allow us to collaborate on the same Ubuntu environment.

**Comment by halffullheart** [comment]
I added my [Vagrant file](/halffullheart/mdr/blob/master/Vagrantfile)

**Comment by madx** [comment]
I think there's no real benefit regarding the complexity of the app. 

Even if I'm quite familiar with Linux I don't really understand how the WebKitGTK package is versionned / distributed. Maybe Arch is doing something funky there or there's really no WebKit2 in Ubuntu (event in trusty!) 

Anyway, I'm going to revert to WebKit 1 for the moment and check that it compiles fine on Arch & Ubuntu.

We might switch back to WebKit 2 when it's more broadly available. It's a matter of changing 1 function call and the `pkg-config` call.

**Comment by halffullheart** [comment]
I’m glad it’s not too big of a change.

**Comment by madx** [comment]
Actually it's a _little_ bit more (just need to add a widget) but nothing harmful ;)
