### ISSUE TITLE
Provide binaries for tagged (pre-)releases?

### ISSUE THREAD

**Issue by yaauie** [halffullheart/mdr#24]
I'd like to help test/document, but without the whole vagrant build environment.

Can you provide binaries for the tagged releases?

**Comment by kud** [comment]
Thanks @yaauie for your interest!

Maybe @madx can give you that. :)

**Comment by madx** [comment]
Yes!

I have to setup the Vagrant build env here to make builds for Ubuntu.

What distro are you using?

**Comment by halffullheart** [comment]
@yaauie I believe you are using a Mac. You can build with just `rake`. This might not be clear from the README, but the Vagrant setup is just for building on Ubuntu from another platform.
