### ISSUE TITLE
Need a stable version tag as soon as possible

### ISSUE THREAD

**Issue by kud** [halffullheart/mdr#26]
As I want to publish `mdr` on `homebrew`, I need a stable version tag as soon as possible.

Do you know when it's possible?

**Comment by halffullheart** [comment]
I would like to get issues #10 and #21 fixed before I tag it with 1.0

Should only take a few hours of work to get it done, but I have been really busy. I would love a pull request!

**Comment by kud** [comment]
Okay, I will try to work on the first issue as I've got a mac. ;)
