### ISSUE TITLE
Please, make `master` branch as default

### ISSUE THREAD

**Issue by kud** [halffullheart/mdr#37]
Stable branch must be the default branch.

**Comment by halffullheart** [comment]
@kud Why would you like to have master be the default? I’d like to use [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) which in my experience works better if you default to develop.

**Comment by kud** [comment]
I don't remember why I asked that but I'm quite sure it's because homebrew takes the default branch to compile.

**Comment by halffullheart** [comment]
Homebrew uses a tagged version, so this shouldn’t be a problem.

**Comment by kud** [comment]
:+1: thanks so :)
